[pytest]
minversion = 6.0
testpaths = datacenter/tests tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -q
markers =
    integration: marks tests as integration that require external services
filterwarnings = ignore::DeprecationWarning
